/**
 * Kadro design tokens for React Native: light and dark colour roles, the native type scale on the
 * static Archivo instances, spacing, radius, elevation, motion and the pitch diagram geometry.
 *
 * Built from theme/tokens.json by scripts/build-tokens.mjs. Edit the JSON and run
 * `pnpm --filter @kadro/brand build`; do not edit this file.
 */

export type ColorScheme = 'light' | 'dark';

/** What the user picked in Ayarlar; `system` follows the device appearance. */
export type ColorPreference = 'system' | 'light' | 'dark';

export type ColorRole =
  | 'background'
  | 'surface'
  | 'surfaceSunken'
  | 'surfaceRaised'
  | 'fillMuted'
  | 'border'
  | 'borderStrong'
  | 'text'
  | 'textMuted'
  | 'inverse'
  | 'onInverse'
  | 'primary'
  | 'onPrimary'
  | 'primaryText'
  | 'link'
  | 'focusRing'
  | 'accent'
  | 'onAccent'
  | 'accentText'
  | 'warning'
  | 'onWarning'
  | 'danger'
  | 'onDanger'
  | 'dangerText'
  | 'pitch'
  | 'pitchLine'
  | 'onPitch'
  | 'pitchMarker'
  | 'onPitchMarker';

export type ColorRoles = Readonly<Record<ColorRole, string>>;

export const colors: Readonly<Record<ColorScheme, ColorRoles>> = {
  light: {
    background: '#F5F6F1',
    surface: '#FFFFFF',
    surfaceSunken: '#EBEEE6',
    surfaceRaised: '#FFFFFF',
    fillMuted: '#E1E6DC',
    border: '#D3D9D0',
    borderStrong: '#6F7D75',
    text: '#0F1A14',
    textMuted: '#4E5E55',
    inverse: '#0F1A14',
    onInverse: '#F5F6F1',
    primary: '#1B7F4B',
    onPrimary: '#FFFFFF',
    primaryText: '#17704A',
    link: '#17704A',
    focusRing: '#17704A',
    accent: '#E35A14',
    onAccent: '#0F1A14',
    accentText: '#0F1A14',
    warning: '#F2C230',
    onWarning: '#0F1A14',
    danger: '#D7263D',
    onDanger: '#FFFFFF',
    dangerText: '#C41E34',
    pitch: '#0E5B36',
    pitchLine: '#F5F6F1',
    onPitch: '#FFFFFF',
    pitchMarker: '#F5F6F1',
    onPitchMarker: '#0F1A14',
  },
  dark: {
    background: '#0C1611',
    surface: '#142019',
    surfaceSunken: '#08100C',
    surfaceRaised: '#1B2A21',
    fillMuted: '#24352B',
    border: '#2A3A30',
    borderStrong: '#6A7A71',
    text: '#F5F6F1',
    textMuted: '#A6B3AA',
    inverse: '#F5F6F1',
    onInverse: '#0C1611',
    primary: '#3DBF78',
    onPrimary: '#0F1A14',
    primaryText: '#3DBF78',
    link: '#3DBF78',
    focusRing: '#F5F6F1',
    accent: '#FF6B1A',
    onAccent: '#0F1A14',
    accentText: '#FF7A33',
    warning: '#F2C230',
    onWarning: '#0F1A14',
    danger: '#FF5C6E',
    onDanger: '#0F1A14',
    dangerText: '#FF5C6E',
    pitch: '#0E5B36',
    pitchLine: '#F5F6F1',
    onPitch: '#FFFFFF',
    pitchMarker: '#F5F6F1',
    onPitchMarker: '#0F1A14',
  },
};

/** Roles with one value in both schemes: the pitch diagram is always night turf with chalk. */
export const fixedColorRoles: readonly ColorRole[] = [
  'pitch',
  'pitchLine',
  'onPitch',
  'pitchMarker',
  'onPitchMarker',
];

export type OverlayRole = 'pressed' | 'scrim';

export const overlays: Readonly<Record<ColorScheme, Readonly<Record<OverlayRole, string>>>> = {
  light: {
    pressed: 'rgba(15, 26, 20, 0.08)',
    scrim: 'rgba(15, 26, 20, 0.48)',
  },
  dark: {
    pressed: 'rgba(245, 246, 241, 0.1)',
    scrim: 'rgba(0, 0, 0, 0.64)',
  },
};

export const palette = {
  pitchGreen: '#1B7F4B',
  pitchGreenText: '#17704A',
  pitchGreenBright: '#3DBF78',
  turfDeep: '#0E5B36',
  nightMatch: '#0C1611',
  nightSunken: '#08100C',
  nightSurface: '#142019',
  nightRaised: '#1B2A21',
  nightFill: '#24352B',
  nightLine: '#2A3A30',
  nightLineStrong: '#6A7A71',
  chalkWhite: '#F5F6F1',
  chalkSunken: '#EBEEE6',
  chalkFill: '#E1E6DC',
  chalkLine: '#D3D9D0',
  chalkLineStrong: '#6F7D75',
  white: '#FFFFFF',
  ink: '#0F1A14',
  orangeBall: '#FF6B1A',
  orangeBallDeep: '#E35A14',
  orangeBallBright: '#FF7A33',
  cardYellow: '#F2C230',
  redCard: '#D7263D',
  redCardText: '#C41E34',
  redCardBright: '#FF5C6E',
  neutral: '#4E5E55',
  neutralOnDark: '#A6B3AA',
} as const;

export type FontRole = 'display' | 'body' | 'numeric';

export type FontWeight = 400 | 500 | 600 | 700 | 800;

export type NativeFontName =
  | 'Archivo-Regular'
  | 'Archivo-Medium'
  | 'Archivo-SemiBold'
  | 'ArchivoCondensed-Bold'
  | 'ArchivoCondensed-ExtraBold';

/** Static instance files, relative to the `@kadro/brand` package root (for `expo-font`). */
export const nativeFontFiles: Readonly<Record<NativeFontName, string>> = {
  'Archivo-Regular': 'fonts/archivo/static/Archivo-Regular.ttf',
  'Archivo-Medium': 'fonts/archivo/static/Archivo-Medium.ttf',
  'Archivo-SemiBold': 'fonts/archivo/static/Archivo-SemiBold.ttf',
  'ArchivoCondensed-Bold': 'fonts/archivo/static/ArchivoCondensed-Bold.ttf',
  'ArchivoCondensed-ExtraBold': 'fonts/archivo/static/ArchivoCondensed-ExtraBold.ttf',
};

export type TypeVariant =
  | 'caption'
  | 'footnote'
  | 'label'
  | 'body'
  | 'bodyStrong'
  | 'title3'
  | 'title2'
  | 'title1'
  | 'display'
  | 'numeral'
  | 'score'
  | 'bib'
  | 'numeralXL';

export interface TextStyleToken {
  readonly role: FontRole;
  /** Static instance name; it already carries the weight and the width. */
  readonly fontFamily: NativeFontName;
  readonly fontSize: number;
  readonly lineHeight: number;
  readonly fontWeight: FontWeight;
  /** Points (the token's em value times the size). */
  readonly letterSpacing: number;
  /** `fontVariant: ['tabular-nums']` for counts, times, fees and kit numbers. */
  readonly tabularNums: boolean;
}

export const typeScale: Readonly<Record<TypeVariant, TextStyleToken>> = {
  caption: {
    role: 'body',
    fontFamily: 'Archivo-Medium',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: 500,
    letterSpacing: 0,
    tabularNums: false,
  },
  footnote: {
    role: 'body',
    fontFamily: 'Archivo-Regular',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: 400,
    letterSpacing: 0,
    tabularNums: false,
  },
  label: {
    role: 'body',
    fontFamily: 'Archivo-SemiBold',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: 600,
    letterSpacing: 0,
    tabularNums: false,
  },
  body: {
    role: 'body',
    fontFamily: 'Archivo-Regular',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: 400,
    letterSpacing: 0,
    tabularNums: false,
  },
  bodyStrong: {
    role: 'body',
    fontFamily: 'Archivo-SemiBold',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: 600,
    letterSpacing: 0,
    tabularNums: false,
  },
  title3: {
    role: 'body',
    fontFamily: 'Archivo-SemiBold',
    fontSize: 20,
    lineHeight: 26,
    fontWeight: 600,
    letterSpacing: 0,
    tabularNums: false,
  },
  title2: {
    role: 'display',
    fontFamily: 'ArchivoCondensed-Bold',
    fontSize: 24,
    lineHeight: 28,
    fontWeight: 700,
    letterSpacing: -0.24,
    tabularNums: false,
  },
  title1: {
    role: 'display',
    fontFamily: 'ArchivoCondensed-Bold',
    fontSize: 32,
    lineHeight: 36,
    fontWeight: 700,
    letterSpacing: -0.32,
    tabularNums: false,
  },
  display: {
    role: 'display',
    fontFamily: 'ArchivoCondensed-ExtraBold',
    fontSize: 40,
    lineHeight: 42,
    fontWeight: 800,
    letterSpacing: -0.4,
    tabularNums: false,
  },
  numeral: {
    role: 'numeric',
    fontFamily: 'ArchivoCondensed-Bold',
    fontSize: 24,
    lineHeight: 28,
    fontWeight: 700,
    letterSpacing: 0,
    tabularNums: true,
  },
  score: {
    role: 'numeric',
    fontFamily: 'ArchivoCondensed-Bold',
    fontSize: 40,
    lineHeight: 44,
    fontWeight: 700,
    letterSpacing: 0,
    tabularNums: true,
  },
  bib: {
    role: 'numeric',
    fontFamily: 'ArchivoCondensed-ExtraBold',
    fontSize: 28,
    lineHeight: 32,
    fontWeight: 800,
    letterSpacing: 0,
    tabularNums: true,
  },
  numeralXL: {
    role: 'numeric',
    fontFamily: 'ArchivoCondensed-ExtraBold',
    fontSize: 64,
    lineHeight: 64,
    fontWeight: 800,
    letterSpacing: 0,
    tabularNums: true,
  },
};

export const spacing = {
  '0': 0,
  '1': 4,
  '2': 8,
  '3': 12,
  '4': 16,
  '5': 20,
  '6': 24,
  '8': 32,
  '10': 40,
  '12': 48,
  '16': 64,
  '20': 80,
  '24': 96,
  '32': 128,
} as const;

export const radius = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 20,
  full: 9999,
} as const;

export interface ShadowToken {
  readonly color: string;
  readonly opacity: number;
  readonly radius: number;
  readonly offsetY: number;
  /** Android elevation. */
  readonly elevation: number;
}

/** The one floating level (sheets, sticky actions). Cards use a hairline, not a shadow. */
export const elevation: Readonly<Record<ColorScheme, ShadowToken>> = {
  light: {
    color: '#0F1A14',
    opacity: 0.12,
    radius: 12,
    offsetY: 8,
    elevation: 6,
  },
  dark: {
    color: '#000000',
    opacity: 0.5,
    radius: 12,
    offsetY: 8,
    elevation: 6,
  },
};

export const motion = {
  duration: {
    press: 120,
    state: 200,
    enter: 320,
    draw: 480,
  },
  easing: {
    standard: 'cubic-bezier(0.22, 1, 0.36, 1)',
    exit: 'cubic-bezier(0.4, 0, 1, 1)',
  },
  stagger: 30,
  animatedProperties: ['transform', 'opacity', 'stroke-dashoffset'],
  reducedMotion: {
    duration: 0,
    opacityFadeMax: 120,
    diagramDrawn: true,
  },
} as const;

export const layout = {
  gutter: 16,
  rowGap: 12,
  groupGap: 24,
  minTouchTarget: 44,
  rowMinHeight: 56,
  controlHeight: 48,
} as const;

export const pitchDiagram = {
  viewBox: [300, 460],
  lineWidth: 2,
  centreCircleRadius: 40,
  centreSpotRadius: 3,
  penaltyBox: {
    width: 180,
    depth: 60,
  },
  goalBox: {
    width: 90,
    depth: 22,
  },
  markerRadius: 18,
  markerStroke: 2,
  emptyMarkerDash: '4 4',
  benchChipHeight: 32,
} as const;

export const state = {
  rsvp: {
    in: {
      fill: 'primary',
      on: 'onPrimary',
      text: 'primaryText',
    },
    maybe: {
      fill: 'warning',
      on: 'onWarning',
      text: 'text',
    },
    out: {
      fill: 'danger',
      on: 'onDanger',
      text: 'dangerText',
    },
    waitlist: {
      fill: 'surface',
      on: 'textMuted',
      text: 'textMuted',
      outline: 'borderStrong',
    },
    locked: {
      fill: 'fillMuted',
      on: 'textMuted',
      text: 'textMuted',
      icon: 'lock',
    },
  },
  match: {
    draft: 'textMuted',
    open: 'primaryText',
    locked: 'textMuted',
    played: 'text',
    cancelled: 'dangerText',
  },
  chip: {
    rest: {
      fill: 'fillMuted',
      on: 'text',
    },
    selected: {
      fill: 'inverse',
      on: 'onInverse',
    },
  },
  sample: {
    fill: 'warning',
    on: 'onWarning',
    label: 'ÖRNEK',
  },
  verified: {
    icon: 'check',
    color: 'primaryText',
    label: 'Doğrulanmış',
  },
} as const;

export const theming = {
  preferences: ['system', 'light', 'dark'],
  defaultPreference: 'system',
  storageKey: 'kadro.colorScheme',
  labels: {
    system: 'Sistem',
    light: 'Açık',
    dark: 'Koyu',
  },
} as const;
