package app.cetele.android.core.network.dto.problem

object ProblemCodes {
    const val AUTH_UNAUTHENTICATED = "auth.unauthenticated"
    const val AUTH_INTEGRITY_REQUIRED = "auth.integrity_required"
    const val AUTH_INTEGRITY_INVALID = "auth.integrity_invalid"
    const val AUTH_OTP_INVALID = "auth.otp_invalid"
    const val AUTH_REFRESH_INVALID = "auth.refresh_invalid"
    const val FORBIDDEN = "forbidden"
    const val NOT_FOUND = "not_found"
    const val VALIDATION_FAILED = "validation.failed"
    const val CONFLICT = "conflict"
    const val MEMBERSHIP_OWNER_LOCKED = "membership.owner_locked"
    const val MEMBERSHIP_ALREADY_MEMBER = "membership.already_member"
    const val RATE_LIMITED = "rate_limited"
    const val PAYLOAD_TOO_LARGE = "payload_too_large"
    const val UNSUPPORTED_MEDIA_TYPE = "unsupported_media_type"
    const val SERVER_ERROR = "server_error"
    const val AUTH_REAUTH_INVALID = "auth.reauth_invalid"
    const val CUSTOMER_DELETED = "customer.deleted"
    const val LEDGER_ALREADY_REVERSED = "ledger.already_reversed"
    const val LEDGER_REVERSAL_MISMATCH = "ledger.reversal_mismatch"
    const val PLAN_CUSTOMER_LIMIT = "plan.customer_limit"
    const val PLAN_PHOTO_LIMIT = "plan.photo_limit"
    const val SMS_QUOTA_EXCEEDED = "sms.quota_exceeded"
    const val SMS_DAILY_CAP_REACHED = "sms.daily_cap_reached"
    const val SMS_CONSENT_MISSING = "sms.consent_missing"
    const val SMS_PHONE_MISSING = "sms.phone_missing"
    const val SMS_PROVIDER_FAILED = "sms.provider_failed"
    const val REMINDER_NO_BALANCE = "reminder.no_balance"
    const val STATEMENT_LINK_LIMIT = "statement.link_limit"
    const val MEDIA_INVALID = "media.invalid"
    const val MEDIA_NOT_UPLOADED = "media.not_uploaded"
    const val MEDIA_TOO_LARGE = "media.too_large"
    const val MEDIA_NOT_READY = "media.not_ready"
    const val ACCOUNT_OWNER_OF_SHARED_SHOP = "account.owner_of_shared_shop"
    const val ACCOUNT_DELETION_PENDING = "account.deletion_pending"
    const val SHOP_DELETION_PENDING = "shop.deletion_pending"
}
