// Writes the consumer files of the design tokens from `theme/tokens.json`:
//   theme/theme.css  custom properties for the web (light on :root, dark by attribute or system)
//   theme/tokens.ts  typed light and dark objects for React Native (no CSS)
// `node scripts/build-tokens.mjs` writes both files; `--check` exits 1 when either is stale.
/* eslint-disable security/detect-object-injection, security/detect-non-literal-fs-filename -- offline build-time script: every key comes from this package's own token file and every path stays inside the package. */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = 'theme/tokens.json';
export const OUTPUTS = { css: 'theme/theme.css', ts: 'theme/tokens.ts' };

/** `fillMuted` -> `fill-muted`, `numeralXL` -> `numeral-xl`. */
const kebab = (name) =>
  name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
    .toLowerCase();

const lowerHex = (value) => (/^#[0-9A-Fa-f]{6}$/.test(value) ? value.toLowerCase() : value);

const HEADER_NOTE = [
  `Built from ${SOURCE} by scripts/build-tokens.mjs. Edit the JSON and run`,
  '`pnpm --filter @kadro/brand build`; do not edit this file.',
].join('\n * ');

function colorBlock(tokens, scheme, { withFixed }) {
  const fixed = new Set(tokens.color.fixedRoles);
  const lines = [`  color-scheme: ${scheme};`];
  for (const [role, value] of Object.entries(tokens.color.theme[scheme])) {
    if (!withFixed && fixed.has(role)) continue;
    lines.push(`  --k-color-${kebab(role)}: ${lowerHex(value)};`);
  }
  for (const [name, value] of Object.entries(tokens.color.overlay[scheme])) {
    lines.push(`  --k-overlay-${kebab(name)}: ${value};`);
  }
  for (const [level, value] of Object.entries(tokens.elevation[scheme])) {
    lines.push(`  --k-elevation-${level.replace('level', '')}: ${value};`);
  }
  return lines;
}

function typeLines(tokens, scale, { full }) {
  const t = tokens.typography;
  const lines = [];
  for (const [variant, entry] of Object.entries(scale)) {
    const name = kebab(variant);
    lines.push(`  --k-type-${name}-size: ${entry.size}px;`);
    lines.push(`  --k-type-${name}-line-height: ${entry.lineHeight}px;`);
    if (!full) continue;
    lines.push(`  --k-type-${name}-weight: ${entry.weight};`);
    lines.push(`  --k-type-${name}-stretch: ${t.fontWidth[entry.family]}%;`);
    lines.push(`  --k-type-${name}-tracking: ${t.letterSpacing[entry.family]}em;`);
  }
  return lines;
}

export function buildCss(tokens) {
  const t = tokens.typography;
  const shared = [
    `  --k-font-family: '${t.fontFamily.body}', ${t.fallbackStack};`,
    ...Object.entries(t.fontWidth).map(([role, width]) => `  --k-font-stretch-${role}: ${width}%;`),
    `  --k-font-numeric: ${t.fontFeature.numeric};`,
    ...typeLines(tokens, t.scale, { full: true }),
    `  --k-measure-prose: ${t.measure.proseMaxCh}ch;`,
    ...Object.entries(tokens.spacing).map(([step, value]) => `  --k-space-${step}: ${value}px;`),
    ...['xs', 'sm', 'md', 'lg', 'full'].map(
      (name) => `  --k-radius-${name}: ${tokens.radius[name]}px;`,
    ),
    ...Object.entries(tokens.motion.duration).map(
      ([name, value]) => `  --k-motion-${kebab(name)}: ${value}ms;`,
    ),
    ...Object.entries(tokens.motion.easing).map(
      ([name, value]) => `  --k-ease-${kebab(name)}: ${value};`,
    ),
    `  --k-motion-stagger: ${tokens.motion.stagger}ms;`,
    `  --k-layout-max-width: ${tokens.layout.web.maxWidth}px;`,
    `  --k-layout-gutter: ${tokens.layout.web.gutter}px;`,
    `  --k-layout-page-gutter: ${tokens.layout.web.pageGutter}px;`,
    `  --k-layout-nav-height: ${tokens.layout.web.navHeight}px;`,
  ];
  const dark = colorBlock(tokens, 'dark', { withFixed: false }).map((line) => `  ${line}`);
  const small = tokens.layout.web.breakpoints.sm - 1;
  const reduced = Object.keys(tokens.motion.duration).map(
    (name) => `    --k-motion-${kebab(name)}: ${tokens.motion.reducedMotion.duration}ms;`,
  );
  return [
    `/*`,
    ` * Kadro theme: colour roles for the light and dark schemes, type, spacing, radius, elevation`,
    ` * and motion as custom properties.`,
    ` *`,
    ` * Scheme selection: light by default; \`data-theme="dark"\` forces dark; \`data-theme="light"\``,
    ` * forces light; \`data-theme="system"\` or no attribute follows \`prefers-color-scheme\`. The`,
    ` * pitch roles (--k-color-pitch*) are the same in both schemes: the diagram is always night turf.`,
    ` *`,
    ` * ${HEADER_NOTE}`,
    ` */`,
    ``,
    `:root,`,
    `[data-theme='light'] {`,
    ...colorBlock(tokens, 'light', { withFixed: true }),
    `}`,
    ``,
    `:root {`,
    ...shared,
    `}`,
    ``,
    `[data-theme='dark'] {`,
    ...colorBlock(tokens, 'dark', { withFixed: false }),
    `}`,
    ``,
    `@media (prefers-color-scheme: dark) {`,
    `  :root:not([data-theme]),`,
    `  [data-theme='system'] {`,
    ...dark,
    `  }`,
    `}`,
    ``,
    `@media (max-width: ${small}px) {`,
    `  :root {`,
    `    --k-layout-page-gutter: ${tokens.layout.web.pageGutterMobile}px;`,
    ...typeLines(tokens, t.scaleWebMobile, { full: false }).map((line) => `  ${line}`),
    `  }`,
    `}`,
    ``,
    `@media (prefers-reduced-motion: reduce) {`,
    `  :root {`,
    ...reduced,
    `  }`,
    `}`,
    ``,
  ].join('\n');
}

const quote = (value) => `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const key = (name) => (/^[A-Za-z_$][\w$]*$/.test(name) ? name : quote(name));

/** Object literal in Prettier's layout (2-space indent, trailing commas, single quotes). */
function literal(value, indent = 0) {
  const pad = ' '.repeat(indent);
  if (Array.isArray(value)) {
    const inner = value.map((item) => literal(item, indent + 2));
    const flat = `[${inner.join(', ')}]`;
    if (flat.length + indent < 80 && !flat.includes('\n')) return flat;
    return `[\n${inner.map((item) => `${pad}  ${item},`).join('\n')}\n${pad}]`;
  }
  if (value && typeof value === 'object') {
    const entries = Object.entries(value).map(
      ([name, item]) => `${key(name)}: ${literal(item, indent + 2)}`,
    );
    if (entries.length === 0) return '{}';
    return `{\n${entries.map((entry) => `${pad}  ${entry},`).join('\n')}\n${pad}}`;
  }
  if (typeof value === 'string') return quote(value);
  return String(value);
}

const union = (names) => {
  const flat = names.map(quote).join(' | ');
  return flat.length < 70
    ? ` ${flat};`
    : `\n${names.map((name) => `  | ${quote(name)}`).join('\n')};`;
};

export function buildTs(tokens) {
  const t = tokens.typography;
  const roles = Object.keys(tokens.color.theme.light);
  const variants = Object.keys(t.scaleMobile);
  const nativeNames = Object.keys(t.fontFiles.static);
  const typeScale = Object.fromEntries(
    variants.map((variant) => {
      const entry = t.scaleMobile[variant];
      const tracking = Math.round(entry.size * t.letterSpacing[entry.family] * 100) / 100;
      return [
        variant,
        {
          role: entry.family,
          fontFamily: t.nativeFamily[entry.family][String(entry.weight)],
          fontSize: entry.size,
          lineHeight: entry.lineHeight,
          fontWeight: entry.weight,
          letterSpacing: tracking === 0 ? 0 : tracking,
          tabularNums: entry.family === 'numeric',
        },
      ];
    }),
  );
  const nativeFontFiles = Object.fromEntries(
    nativeNames.map((name) => [name, t.fontFiles.static[name].file]),
  );
  const elevation = tokens.elevation.native;
  return `/**
 * Kadro design tokens for React Native: light and dark colour roles, the native type scale on the
 * static Archivo instances, spacing, radius, elevation, motion and the pitch diagram geometry.
 *
 * ${HEADER_NOTE}
 */

export type ColorScheme = 'light' | 'dark';

/** What the user picked in Ayarlar; \`system\` follows the device appearance. */
export type ColorPreference = 'system' | 'light' | 'dark';

export type ColorRole =${union(roles)}

export type ColorRoles = Readonly<Record<ColorRole, string>>;

export const colors: Readonly<Record<ColorScheme, ColorRoles>> = ${literal(
    Object.fromEntries(['light', 'dark'].map((scheme) => [scheme, tokens.color.theme[scheme]])),
  )};

/** Roles with one value in both schemes: the pitch diagram is always night turf with chalk. */
export const fixedColorRoles: readonly ColorRole[] = ${literal(tokens.color.fixedRoles)};

export type OverlayRole = 'pressed' | 'scrim';

export const overlays: Readonly<Record<ColorScheme, Readonly<Record<OverlayRole, string>>>> = ${literal(
    tokens.color.overlay,
  )};

export const palette = ${literal(tokens.color.palette)} as const;

export type FontRole = 'display' | 'body' | 'numeric';

export type FontWeight = 400 | 500 | 600 | 700 | 800;

export type NativeFontName =${union(nativeNames)}

/** Static instance files, relative to the \`@kadro/brand\` package root (for \`expo-font\`). */
export const nativeFontFiles: Readonly<Record<NativeFontName, string>> = ${literal(nativeFontFiles)};

export type TypeVariant =${union(variants)}

export interface TextStyleToken {
  readonly role: FontRole;
  /** Static instance name; it already carries the weight and the width. */
  readonly fontFamily: NativeFontName;
  readonly fontSize: number;
  readonly lineHeight: number;
  readonly fontWeight: FontWeight;
  /** Points (the token's em value times the size). */
  readonly letterSpacing: number;
  /** \`fontVariant: ['tabular-nums']\` for counts, times, fees and kit numbers. */
  readonly tabularNums: boolean;
}

export const typeScale: Readonly<Record<TypeVariant, TextStyleToken>> = ${literal(typeScale)};

export const spacing = ${literal(tokens.spacing)} as const;

export const radius = ${literal(
    Object.fromEntries(['xs', 'sm', 'md', 'lg', 'full'].map((name) => [name, tokens.radius[name]])),
  )} as const;

export interface ShadowToken {
  readonly color: string;
  readonly opacity: number;
  readonly radius: number;
  readonly offsetY: number;
  /** Android elevation. */
  readonly elevation: number;
}

/** The one floating level (sheets, sticky actions). Cards use a hairline, not a shadow. */
export const elevation: Readonly<Record<ColorScheme, ShadowToken>> = ${literal(elevation)};

export const motion = ${literal(tokens.motion)} as const;

export const layout = ${literal(tokens.layout.mobile)} as const;

export const pitchDiagram = ${literal(tokens.diagram.pitch)} as const;

export const state = ${literal(tokens.state)} as const;

export const theming = ${literal({
    preferences: tokens.theming.preferences,
    defaultPreference: tokens.theming.defaultPreference,
    storageKey: tokens.theming.mobile.storageKey,
    labels: tokens.theming.mobile.labels,
  })} as const;
`;
}

export function readTokens() {
  return JSON.parse(readFileSync(join(root, SOURCE), 'utf8'));
}

/**
 * Both files, formatted with the repository's Prettier (a root dev dependency) so that
 * prettier --check and the drift check agree.
 */
export async function buildAll(tokens = readTokens()) {
  const prettier = await import('prettier');
  const files = { [OUTPUTS.css]: buildCss(tokens), [OUTPUTS.ts]: buildTs(tokens) };
  const formatted = {};
  for (const [file, content] of Object.entries(files)) {
    const filepath = join(root, file);
    const options = (await prettier.resolveConfig(filepath)) ?? {};
    formatted[file] = await prettier.format(content, { ...options, filepath });
  }
  return formatted;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const [file, content] of Object.entries(await buildAll())) {
    const target = join(root, file);
    if (check) {
      let current = '';
      try {
        current = readFileSync(target, 'utf8');
      } catch {
        current = '';
      }
      if (current !== content) {
        stale += 1;
        process.stderr.write(`stale ${file}: run pnpm --filter @kadro/brand build\n`);
      }
    } else {
      writeFileSync(target, content);
      process.stdout.write(`wrote ${file}\n`);
    }
  }
  if (stale) process.exit(1);
}
